packages:
  - astro-app
  - studio

catalog:
  "@sanity/astro": ^3.2.10
  "@sanity/client": ^7.12.0
  "@sanity/eslint-config-studio": ^5.0.2
  "@sanity/image-url": ^1.2.0
  "@sanity/types": ^4.10.2
  "@sanity/vision": ^4.10.2
  "@types/react": ^19.2.2
  "@biomejs/biome": ^2.2.5
  react: ^19.2.0
  react-dom: ^19.2.0
  sanity: ^4.10.2
  typescript: ^5.9.3
  vite: ^7.1.9
