packages:
  - "astro-app"
  - "studio"

catalog:
  sanity: ^4.10.2
  "@sanity/vision": ^4.10.2
  "@sanity/types": ^4.10.2
  "@sanity/image-url": ^1.2.0
  "@sanity/client": ^7.12.0
  "@sanity/astro": ^3.2.10
  "@sanity/eslint-config-studio": ^5.0.2
  typescript: ^5.9.3
  prettier: ^3.6.2
  eslint: ^9.37.0
  vite: ^7.1.9

  react: ^19.2.0
  react-dom: ^19.2.0
  "@types/react": ^19.2.2
